### PR TITLE
fix(build): Fixed support for SystemJS index imports

### LINKED ISSUE #4: Error with 3.0.0
I've just updated to 3.0.0 and this is the error i'm getting 

```
SyntaxError: Unexpected token < 
at Object.eval (http://localhost:2000/node_modules/@ngrx/store-log-monitor/index.js:4:22)
```

It has something to do with me using system.js, but everything worked perfectly in an earlier release. 

P.S 

This is the line in index.js:

```
var dock_monitor_1 = require('./dock-monitor');
```

### PR DESCRIPTION
**Pull request by brandonroberts**
Closes #4

### CODE REVIEW

**Comment by attilacsanyi** [comment]
Hopefully this PR will be accepted soon 😉 Thx guys in advance!

**Comment by attilacsanyi** [comment]
Dear @MikeRyan52 can you please verify this PR from @brandonroberts ?
I cannot use store-log-monitor module with systemjs and angular RC5 without this fix, thanks in advance.

**Comment by dchacke** [comment]
+1, would love this soon

**Comment by SamVerschueren** [comment]
Friendly ping :).

**Comment by MikeRyanDev** [comment]
Fixed in v3.0.2

**Pull request closed without merging**
